# -*- makefile -*-
# Makefile for Digital Unix V4.0 with cxx compiler and Posix threads

CC = cxx
#DEFS = 
DEFS = -DPTHREADS

CFLAGS =  -pthread -c -g3 -O5 $(DEFS)
#CFLAGS =  -pthread -c -g -O0 $(DEFS)

LD = $(CC)
LDFLAGS = -g -pthread

AR = ar
ARFLAGS = -cru

RANLIB = true

STDLIBS=

#TASK_OBJ = ctask.o async.o
TASK_OBJ = ptask.o

include makefile.uni
