# -*- makefile -*-
# Makefile for Windows with MinGW

CC = g++

CFLAGS = -Wall -c -O5 -g $(DEFS)
#CFLAGS = -Wall -c -g $(DEFS)

LD = $(CC)
LDFLAGS = -g

AR = ar
ARFLAGS = -cru

RANLIB = true

STDLIBS=-lwsock32

include makefile.uniwin
