# -*- makefile -*-
# Makefile for Linux with gcc compiler with Posix threads library

CC = g++ -fno-exceptions
#DEFS = 
DEFS = -DPTHREADS 

#CFLAGS = -Wall -c -O0 -g $(DEFS)
CFLAGS = -Wall -c -O5 -g $(DEFS)

LD = $(CC)
LDFLAGS = -g

AR = ar
ARFLAGS = -cru

RANLIB = true

STDLIBS= -L/lib -lpthread

#TASK_OBJ = ctask.o async.o
TASK_OBJ = ptask.o

include makefile.uni
