# -*- makefile -*-
# Makefile for FreeBSD 3.0 with g++ compiler and Posix threads

CC = g++
#DEFS = 
DEFS = -DPTHREADS -D_THREADSAFE

CFLAGS =  -c -g3 -O5 $(DEFS)
#CFLAGS =  -c -g -O0 $(DEFS)

LD = $(CC)
LDFLAGS = -pthread

AR = ar
ARFLAGS = -cru

RANLIB = ranlib

STDLIBS =

TASK_OBJ = ptask.o

