# -*- makefile -*-
# Makefile for FreeBSD with g++ compiler and portable threads

CC = g++
DEFS = 

CFLAGS =  -c -g3 -O5 $(DEFS)
#CFLAGS =  -c -g -O0 $(DEFS)

LD = $(CC)
LDFLAGS = 

AR = ar
ARFLAGS = -cru

RANLIB = ranlib

STDLIBS =

TASK_OBJ = ctask.o async.o

include makefile.uni
