# -*- makefile -*-
# Makefile for Solaris with gcc compiler and Posix threads

CC = gcc
#DEFS =
DEFS = -DPTHREADS -D_REENTRANT 

CFLAGS =  -c -O5 $(DEFS)
#CFLAGS =  -c -g -O0 $(DEFS)

LD = $(CC)
LDFLAGS = -g

AR = ar
ARFLAGS = -cru

RANLIB = true

STDLIBS=-lnsl -lsocket -lpthread 

#TASK_OBJ = ctask.o async.o
TASK_OBJ = ptask.o

include makefile.uni
